[tool.poetry]
name = "docker-diagrams"
description = "docker-diagrams"
version = "0.0.0-dev"
authors = ["mingrammer <mingrammer@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8.2"
diagrams = "0.8.2"
